version: '3.7'

networks:
  php8-network:
    driver: bridge

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: always
    tty: true
    depends_on:
      - php
      - redis
      - phpmyadmin
      - mysql-mymarket
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    networks:
      - php8-network

  php:
    build: ./docker/php
    restart: always
    tty: true
    container_name: php
    links:
      - redis
      - phpmyadmin
      - mysql-mymarket
      - mysql-catalog
    networks:
      - php8-network
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www

  mysql-catalog:
    image: mysql:8.0.23
    tty: true
    restart: always
    container_name: mysql-catalog
    networks:
      - php8-network
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/catalog/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro'
      - './docker/mysql/catalog/database:/var/lib/mysql'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catalog

  mysql-mymarket:
    image: mysql:8.0.23
    tty: true
    restart: always
    container_name: mysql-mymarket
    networks:
      - php8-network
    ports:
      - '3307:3307'
    volumes:
      - './docker/mysql/mymarket/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro'
      - './docker/mysql/mymarket/database:/var/lib/mysql'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mymarket

  phpmyadmin:
    image: library/phpmyadmin
    container_name: phpmyadmin
    tty: true
    networks:
      - php8-network
    depends_on:
      - mysql-mymarket
      - mysql-catalog
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOSTS: mysql-mymarket
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '8080:80'

  redis:
    image: bitnami/redis:latest
    restart: always
    tty: true
    container_name: redis
    volumes:
      - ./docker/redis:/bitnami/redis/data
    networks:
      - php8-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
