version: '3.7'

networks:
  frontend:
    external:
      name: proxy_proxy
  backend:

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: always
    tty: true
    environment:
      - VIRTUAL_HOST=mymarket.test
    depends_on:
      - php
      - redis
      - phpmyadmin
      - mysql-catalog
    volumes:
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    networks:
      - frontend
      - backend

  php:
    build: ./docker/php
    restart: always
    tty: true
    container_name: php
    links:
      - redis
      - phpmyadmin
      - mysql-catalog
    networks:
      - backend
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www

# БД для каталога
  mysql-catalog:
    image: mysql:8.0.0
    tty: true
    restart: always
    container_name: mysql-catalog
    networks:
      - backend
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/catalog/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro'
      - './docker/mysql/catalog/database:/var/lib/mysql'
    environment:
      - MYSQL_USER=mymarket
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catalog

  phpmyadmin:
    image: library/phpmyadmin
    container_name: phpmyadmin
    tty: true
    networks:
      - frontend
      - backend
    depends_on:
      - mysql-catalog
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOSTS: mysql-catalog
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      VIRTUAL_HOST: pma.mymarket.test
    ports:
      - '8080:80'

  redis:
    image: bitnami/redis:latest
    restart: always
    tty: true
    container_name: redis
    volumes:
      - ./docker/redis:/bitnami/redis/data
    networks:
      - backend
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
